name: telegram_bot
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.10.1

dependencies:
  path: ^1.9.0
  teledart: ^0.6.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

executables:
  telegram_bot: main
